### ISSUE TITLE
add methods to get registry data 

### ISSUE THREAD

**Issue by yochannah** [intermine/imjs#22]
registry.intermine.org allows you to programatically access a list of InterMines. Add methods to the InterMine registry to fetch all InterMines and return them.

See the [python tutorial](https://github.com/intermine/intermine-ws-python-docs/blob/master/00-tutorial.ipynb) for the registry to get an idea of possible useful methods.

**Comment by LakshSingla** [comment]
@yochannah I would like to take up this issue :smile: But I am new to CoffeeScript and may take a while before I can get started. Are you planning on decaffeinating it soon (w.r.t #25) ?

**Comment by yochannah** [comment]
@LakshSingla I don't think it'll be anytime really soon, and it's not even for sure, unfortunately!

**Comment by LakshSingla** [comment]
All right!! Lemme look up on coffescript docs and get back to you :smile:

**Comment by yochannah** [comment]
awesome :heart: you know where to find me for questions

**Comment by LakshSingla** [comment]
@yochannah I have read up on CoffeeScript syntax and now know a little better about constraints and queries in intermine !!! I figured that we need to query `http://registry.intermine.org/service/instances` and we will get the required data, but some of it is irrelevant to our purposes. According to you, what all should we extract (for regular purposes) and what all should we filter out ?? :smile:  
Here is a sample object from the array returned: 
```
{
      "_id": "5a0059432f20910011ef9a34",
      "id": "42",
      "name": "BMAP",
      "url": "https://bmap.jgi.doe.gov/bmapmine/",
      "created_at": "2017-11-06T12:44:51.288Z",
      "last_time_updated": "2019-02-18T00:00:23.237Z",
      "status": "Running",
      "isProduction": true,
      "twitter": "",
      "description": "Brassicales Map Alignment Project",
      "api_version": "19",
      "intermine_version": "1.7.1",
      "release_version": "1.1",
      "__v": 2,
      "maintainerOrgName": "",
      "maintainerUrl": "",
      "images": {
        "small": "http://intermine.readthedocs.org/en/latest/_static/img/logo.png" (truncated)
      },
      "colors": {
        "header": {
          "main": "#609c42",
          "text": "#fff"
        },
        "main": {
          "fg": "#595455",
          "bg": "#fff"
        },
        "focus": {
          "fg": "#fff",
          "bg": "#829b02"
        }
      },
      "location": {
        "latitude": "37.932370",
        "longitude": "-121.9042"
      },
      "organisms": [
        "A. linifolium" (truncated)
      ],
      "neighbours": [
        "Plants"
      ]
    },
```

**Comment by yochannah** [comment]
oh, that's a good question @LakshSingla! I think it probably doesn't hurt to leave most of the things there, actually. 

The following keys aren't interesting but I don't think it's crucial to filter them out - you can if you like! 

```json
      "_id": "5a0059432f20910011ef9a34",
      "created_at": "2017-11-06T12:44:51.288Z",
      "last_time_updated": "2019-02-18T00:00:23.237Z",
      "status": "Running",
      "__v": 2
```

**Comment by LakshSingla** [comment]
Also, 
 - In which file should I start writing this helper method ? It seems that adding it in `service.coffee`           would be misleading` ?
- I would be exposing it as `fetchAllMines()` to the JS clients
- As it is an asynchronous action, should I be accepting a callback of the form of `function(err, result)` (common NodeJS pattern) used throughout the application ?

**Comment by yochannah** [comment]
@LakshSingla 

- maybe we should make a new file, registry.coffee?
- `fetchAllMines()` sounds perfect
- Yes, follow existing behaviours for consistency's sake. Here's one example: the method returns a promise but optionally accepts a callback as well: 

https://github.com/intermine/imjs/blob/5f48d6c716ef135a14a118c21a9ad377344d5bef/src/service.coffee#L493-L505

That same method in use, here: https://jsbin.com/vacefe/edit?html,console

I suspect most of the time we'd only want promises, not callbacks, but it makes sense to keep it consistent with the rest of the library. :+1:

**Comment by LakshSingla** [comment]
@yochannah Sorry for a late response :disappointed:. 

Regarding this issue, I have created a file which is accessing the data and is kept consistent with the codebase. Here is the link to it [`registry.js`](https://github.com/LakshSingla/imjs/blob/dev/src/registry.coffee). (PS: It is a crude version, some refactoring along with unit tests and documentation is required)

I will create a PR once I go through the repository to find any common patterns I may be missing.

**Comment by yochannah** [comment]
No need to apologise at all! This looks like a great start, thogh as you say, docs etc. will make it even better :) 

setting up tests is a bit of a pain - if you have any difficulty I'd suggest just doing the testing via travis (on your own fork) and not bothering setting things up on your local machine. We'd like to fix this (see #9) but we aren't there yet.

**Comment by CodHeK** [comment]
@yochannah probably once #29 gets merged, being inspired by this [link](https://github.com/intermine/intermine-ws-python-docs/blob/master/00-tutorial.ipynb) I can add the `getInfo()` and `getData()` methods ?

**Comment by yochannah** [comment]
@CodHeK that's a very insightful idea! In this case I don't think it is necessary - people who use the python library are more likely to be biologists who are unfamiliar with intermines and may want to explore the data inside the various mines. The Javascript library, however, is mostly (to my knowledge, at least) used by software developers working on applications rather than exporing the data, if that makes sense? 

Great idea though!

**Comment by CodHeK** [comment]
But, I think if we do add the `fetchAllMines` from the Registry, we too should add the other methods that way one can actually embed the features of the registry into their web application  ...

**Comment by LakshSingla** [comment]
@CodHeK can you open a new issue for a separate discussion please. Limiting one discussion to a single issue helps in self documenting the repository so that one can objectively point to this issue at a later stage of time if something goes wrong or for reference without ambiguity. You may provide a reference to this issue from the new one.

**Comment by yochannah** [comment]
reviewing old issues - this one was solved ages ago 🎉
