### ISSUE TITLE
Build failing on travis

### ISSUE THREAD

**Issue by yochannah** [intermine/imjs#23]
The travis build is failing, and I'm guessing it's because InterMine has updated the way it gets built from ant to gradle.

This is the line where it's failing: https://travis-ci.org/intermine/imjs/jobs/483413283#L453 

@julie-sullivan do you happen to know the quick fix to this? (No worries if it's not quick, I can dig into it later).

**Comment by yochannah** [comment]
Okay, some digging and tweaking has been done to use the new intermine testmine config, but the script fails partway through - see https://travis-ci.org/yochannah/imjs/builds/486017491 - it looks like the [DIR variable](https://github.com/intermine/intermine/blob/dev/testmine/setup.sh#L13) isn't set correctly for travis. I could try looking at what InterMine's build script does to see if it sheds any light.

**Comment by yochannah** [comment]
Changing a bunch of paths in the /config/travis/init.sh has made things a lot better but now the build times out after ~45 minutes - during which it is slowly running the imjs tests. Previous build times were around 4 minutes! Argh. 

I couldn't get the tests to pass on my local machine in the past. Maybe I can now? Maybe they'll be faster?

**Comment by yochannah** [comment]
they still don't pass on my machine, so I'll give up on that avenue for now. 

There are slightly different travis set-up instructiosn in the intermine repo. I've tried emulating these but now the build is failing because the EBI nexus server is down (intermine's build is failing too) so I'l have to come back to this.

**Comment by yochannah** [comment]
@julie-sullivan are you able to help with this at all? I think I'm loading the wrong data judging by the current errors: https://travis-ci.org/yochannah/imjs 

The config is mostly located here: 
https://github.com/yochannah/imjs/blob/master/config/travis/init.sh
and a little here: 
https://github.com/yochannah/imjs/blob/master/.travis.yml

**Comment by yochannah** [comment]
Probably also worth referencing this: https://travis-ci.org/yochannah/imjs/builds/486879441 here the intermine build _worked_, but it timed out after 50 minutes. When tests last worked, they usually completed the full build and testing process in under 5 minutes.

**Comment by julie-sullivan** [comment]
Very weird:

```
* What went wrong:
Execution failed for task ':webapp:tomcatStartWar'.
> Web-server is already running.
```

Which makes no sense.

**Comment by yochannah** [comment]
I had this problem when I tried to get them running locally, too!!

**Comment by yochannah** [comment]
I'd find 4 or 5 different java processes I had to terminate through top each time :expressionless:

**Comment by julie-sullivan** [comment]
> I'd find 4 or 5 different java processes I had to terminate through top each time

that might make sense if you were running tests over and over. Maybe a failing test kept a process open?

it makes less sense for travis which should only be running `tomcatStartWar` once, and is a new env every time.

**Comment by yochannah** [comment]
that was what I assumed at the time - failures were leaving something open
that shouldn't be. I'm not sure if it'll be any help at all but figured I
should mention it might not be a one-off :)

**Comment by julie-sullivan** [comment]
Fixed now!

I'll try to remember if we update travis on intermine/intermine to update it here!

**Comment by yochannah** [comment]
WOW - thank you!

Previously we didn't have travis set to periodic builds, so it actually took months to notice. it'll show up faster now because builds won't just be on-demand.
