### ISSUE TITLE
imjs npm package seems to be broken

### ISSUE THREAD

**Issue by heralden** [intermine/imjs#63]
Using imjs via node produces no output. When you run a query, the promise will never be delivered, causing no errors or output to appear. Tested with `rows` method, using many different queries and mines on node v13.2.0. I also tested using my local imjs repo as the package, but same result.

Thanks to @jshreyans for reporting.

**Comment by yochannah** [comment]
hmmm, this is a regression of https://github.com/intermine/imjs/issues/54, possibly? See also https://github.com/intermine/imjs/issues/41 - once we fix this we should make sure the CI tests for it.

**Comment by heralden** [comment]
Turns out this is caused by #65 (ie. happens for https services). The promise actually gets rejected, but it isn't caught hence any errors get swallowed up. I believe Jest defines an `unhandledRejection` listener to throw the error, which explains why the error was visible during testing.
