### ISSUE TITLE
Testing: migrate to mocked nodejs http responses rather than requiring a running intermine

### ISSUE THREAD

**Issue by yochannah** [intermine/imjs#9]
See https://github.com/intermine/imjs/tree/master/test for more details on how tests are currently run. It can be quite time consuming to get a local test intermine up and running just for testing purposes, and if you try to run the tests against an InterMine on the internet it is possible to end up with responses timing out. It would be much nicer to test against stubbed methods, instead.

This is a time-consuming enough effort that it's not likely I'll have time to dedicate to it anytime soon. Others are welcome to pick up the issue if they think they have time and know what to do! I can provide help with this if needed.

**Comment by yochannah** [comment]
Popping by to emphatically support this approach further. #23 has taken up way too much time already and shouldn't be necessary.

**Comment by julie-sullivan** [comment]
This is of course the right thing to do. 

Just for the record, we use `imjs` to test the web services in InterMine. We used to have mockhttp requests and THOSE took up way too much time. That's why we use `imjs` and python tests. Mock HTTP calls in Java are a nightmare.

It's wrong to use these unit tests to test the InterMine web services AND imjs itself. Too many moving parts! 

However if we update imjs to (correctly) not use "live" web services, we need another solution to test web services in InterMine. 

(#23 only took me a few minutes to fix btw)

**Comment by yochannah** [comment]
I'm in favour of leaving the tests in place as integration tests - integration tests *definitely* have a place in software development. A couple of ideas: 

1. It might be the integration tests belong in a different package entirely that simply *uses* imjs, 
2. or maybe we can leave them in this repo and re-use them, but tell the tests whether to use the running intermine as a fixture or whether to use mocked responses. 

It's also a slight concern to me that the langauge that tests the web services isn't necessarily one that is known by the person implementing the web services, so they may not be able to write their own tests (coffeescript vs java).

**Comment by LakshSingla** [comment]
While investigating the dependencies I can look up on some of the libraries which allow us to mock the HTTP requests. I am a bit confused as to how `imjs` is used to test the live web services. Does it mean that the unit tests in this repo not only test the correct functioning of the library but also ensure correctness of the response one gets from the Intermine servers?

**Comment by yochannah** [comment]
Exactly that! If you look here: https://github.com/intermine/intermine/blob/dev/config/travis/init.sh#L62 you can see that the intermine server code checks out imjs and runs tests on its side, and if you look at the travis config for imjs you can see it tests against a freshly cloned intermine server. 

Basically what we have is more like integration tests and less like unit tests. Good SO answer on what the difference is: https://stackoverflow.com/questions/5357601/whats-the-difference-between-unit-tests-and-integration-tests

**Comment by yochannah** [comment]
Reviewing old issues - @LakshSingla solved this! 🏆
